
.PHONY:all clean

all:syscall548 noblock_read_write poll_test signal_test memory_area oom_triger \
	mmap_test test_dev_test

clean:
	rm -f syscall548 noblock_read_write poll_test signal_test memory_area oom_triger \
	mmap_test test_dev_test